### ISSUE TITLE
Synchronous contract calls: concordium client

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-client#108]
**Task description**

In connection with https://github.com/Concordium/concordium-node/issues/236 concordium-client needs to be updated to support V1 contracts.

The high-level requirements are
- concordium-client must still allow to deploy and inspect existing contract types, as well as working with new contracts
- add ability to invoke contracts locally on the node (InvokeContract endpoint)

There should be a general change in handling module deployment. Previously concordium-client added the module version and took just a wasm file as input. In order to reduce errors this should be changed. cargo-concordium will be changed to output a versioned output.

To support deployment of raw Wasm modules we could still support a `--version` option which would add that version to a raw wasm file before deployment.

**Sub-tasks**
- [ ] Add raw InvokeContract command to invoke the contract for testing
- [ ] Add a high-level `contract invoke` command that requires less input, or more friendly input, from the user
- [ ] Allow deploying and inspecting V1 modules analogously as V0 are now. The client should figure out itself which version it retrieved. THe main difference between V0 and V1 modules will be in the module schema. V1 modules will have a different schema, and the semantics of entrypoints will be different, which should be reflected in the the pretty output.
