### ISSUE TITLE
Rewrite/refactor client functions and helpers to use V2 GRPC API

### ISSUE THREAD

**Issue by vikt0r0** [Concordium/concordium-client#200]
### Purpose
The client currently interacts with the V1 GRPC API exposed by the node. Migrating it to use the V2 GRPC API has a number of advantages, including, but perhaps not limited to better types and payload deserialization using code generated from protocol buffer schemas.

### To-do:
- [x] Ensure docs and comment conform to proper Haddock formatting where applicable.
- [x] Remove references to network ID altogether as it is unused in the V2 API.
- [x] Ensure that error messages are preserved or at least as good as they were prior to the migration.
- [x] Write feature proposal.
- [x] Remove any reference on the V1 GRPC API.

### Changes
This issue pertains to rewriting/refactoring existing commands and adding helpers to utilize the V2 GRPC API. The commands to be migrated can be grouped into the families of commands - the result of which will be PRs containing the migrations of one or more of the following:
- [x] transaction
  - [x] submit
  - [x] status
  - [x] send
  - [x] send-scheduled
  - [x] deploy-credential
  - [x] send-shielded
  - [x] register-data
- [x] account
  - [x] show
  - [x] list
  - [x] update-keys
  - [x] update-credentials
  - [x] encrypt
  - [x] decrypt
  - [x] show-alias
- [x] module
  - [x] deploy
  - [x] list
  - [x] show
  - [x] inspect
  - [x] name
  - [x] remove-name
- [x] contract
  - [x] show
  - [x] list
  - [x] init
  - [x] update
  - [x] invoke
  - [x] name
  - [x] remove-name
- [x] config
- [x] consensus
  - [x] show-parameters
  - [x] show-chain-parameters
  - [x] chain-update
- [x] block
  - [x] show
- [x] baker
  - [x] generate-keys
  - [x] add
  - [x] remove
  - [x] set-key
  - [x] update-restake
  - [x] update-stake
  - [x] update-url
  - [x] update-delegation-status
  - [x] configure
- [x] delegator
  - [x] add
  - [x] remove
  - [x] configure
- [x] identity
- [x] raw
